services:
  - type: web
    name: climate-risk-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: gunicorn app:app --timeout 180 --workers 1 --threads 4 --bind 0.0.0.0:$PORT
